# Generated by Django 2.1.1 on 2018-09-27 04:42

import apps.call_records_app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='The timestamp of when the call has started', null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, help_text='The timestamp of when the call has finished', null=True, verbose_name='finished at')),
                ('call_id', models.PositiveIntegerField(blank=True, help_text='Unique ID for each call record pair.', null=True, verbose_name='call ID')),
                ('source', models.CharField(help_text='The subscriber phone number that originated the call.', max_length=20, validators=[apps.call_records_app.utils.validators.phone_number_validator], verbose_name='origin phone number')),
                ('destination', models.CharField(blank=True, help_text='The phone number that received the call.', max_length=20, null=True, verbose_name='destination phone number')),
                ('compromised', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='compromised')),
                ('call_duration', models.DurationField(blank=True, null=True, verbose_name='call duration')),
                ('call_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='call cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_call', models.BooleanField(default=False, verbose_name='processed')),
                ('reference_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='reference month')),
                ('reference_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='reference year')),
            ],
            options={
                'verbose_name': 'telephone bill',
                'verbose_name_plural': 'telephone bills',
                'ordering': ['-started_at'],
            },
        ),
    ]
