# Generated by Django 2.1.1 on 2018-09-27 04:57

import apps.call_records_app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('call_records_app', '0001_initial'), ('call_records_app', '0002_auto_20180922_2057'), ('call_records_app', '0003_auto_20180925_0844'), ('call_records_app', '0004_auto_20180927_0153')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, help_text='The timestamp of when the event occurred', null=True, verbose_name='call timestamp')),
                ('call_type', models.PositiveSmallIntegerField(choices=[(1, 'Start'), (2, 'End')], help_text='Indicate if it is a call start or end record.', verbose_name='call type')),
                ('call_id', models.PositiveIntegerField(help_text='Unique ID for each call record pair.', verbose_name='call ID')),
                ('source', models.CharField(blank=True, help_text='The subscriber phone number that originated the call.', max_length=20, null=True, validators=[apps.call_records_app.utils.validators.phone_number_validator], verbose_name='origin phone number')),
                ('destination', models.CharField(blank=True, help_text='The phone number receiving the call.', max_length=20, null=True, verbose_name='destination phone number')),
                ('compromised', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='compromised')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_call', models.BooleanField(default=False, verbose_name='processed call')),
                ('reference_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='reference month')),
                ('reference_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='reference year')),
            ],
            options={
                'verbose_name': 'call record',
                'verbose_name_plural': 'call records',
                'ordering': ['timestamp'],
            },
        ),
    ]
