# Generated by Django 2.1.1 on 2018-09-22 23:57

import apps.call_records_app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_records_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call_id',
            field=models.PositiveIntegerField(blank=True, help_text='Unique ID for each call record pair.', null=True, verbose_name='call ID'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='call_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Start'), (2, 'End')], help_text='Indicate if it is a call start or end record.', null=True, verbose_name='call type'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(blank=True, help_text='The phone number receiving the call.', max_length=20, null=True, verbose_name='destination phone number'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.CharField(help_text='The subscriber phone number that originated the call.', max_length=20, validators=[apps.call_records_app.utils.validators.phone_number_validator], verbose_name='origin phone number'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='The timestamp of when the event occurred.', null=True, verbose_name='call timestamp'),
        ),
    ]
