# Generated by Django 2.1.1 on 2018-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('call_records_app', '0002_auto_20180922_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='processed_call',
            field=models.BooleanField(default=False, verbose_name='processed call'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='reference_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='reference month'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='reference_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='reference year'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='call_id',
            field=models.PositiveIntegerField(help_text='Unique ID for each call record pair.', verbose_name='call ID'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='call_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Start'), (2, 'End')],
                                                   help_text='Indicate if it is a call start or end record.',
                                                   verbose_name='call type'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.CharField(blank=True, help_text='The subscriber phone number that originated the call.',
                                   max_length=20, null=True, verbose_name='origin phone number'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='The timestamp of when the event occurred', null=True,
                                       verbose_name='call timestamp'),
        ),
    ]
